### ISSUE TITLE
Create laser obstacle

### ISSUE THREAD

**Issue by nicolasbock** [video-game-coding-club/maze-runner#89]
To complete this we need to:

- [ ] [Create laser obstacle tiles](#85)
- [ ] [Add new laser tiles to level 0](#86)
- [ ] [Add code to display the laser obstacles](#87)
- [ ] [Add laser animation code](#88)
